// Code generated by "stringer -type=Type"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[MessageDelete-1]
	_ = x[MessageUpdate-2]
	_ = x[MessagePurge-3]
	_ = x[MemberNickname-4]
	_ = x[MemberAvatar-5]
	_ = x[MemberRoles-6]
	_ = x[MemberTimeout-7]
	_ = x[MemberScreening-8]
	_ = x[MemberUpdate-9]
	_ = x[MemberJoin-10]
	_ = x[MemberLeave-11]
	_ = x[MemberBan-12]
	_ = x[MemberUnban-13]
	_ = x[MemberKick-14]
	_ = x[RoleCreate-15]
	_ = x[RoleUpdate-16]
	_ = x[RoleDelete-17]
	_ = x[ServerEdited-18]
	_ = x[ServerEmoji-19]
	_ = x[UserName-20]
	_ = x[UserAvatar-21]
	_ = x[ChannelCreate-22]
	_ = x[ChannelUpdate-23]
	_ = x[ChannelDelete-24]
	_ = x[InviteSend-25]
	_ = x[InviteCreate-26]
	_ = x[InviteDelete-27]
	_ = x[VoiceConnection-28]
	_ = x[VoiceAudioState-29]
}

const _Type_name = "UnknownMessageDeleteMessageUpdateMessagePurgeMemberNicknameMemberAvatarMemberRolesMemberTimeoutMemberScreeningMemberUpdateMemberJoinMemberLeaveMemberBanMemberUnbanMemberKickRoleCreateRoleUpdateRoleDeleteServerEditedServerEmojiUserNameUserAvatarChannelCreateChannelUpdateChannelDeleteInviteSendInviteCreateInviteDeleteVoiceConnectionVoiceAudioState"

var _Type_index = [...]uint16{0, 7, 20, 33, 45, 59, 71, 82, 95, 110, 122, 132, 143, 152, 163, 173, 183, 193, 203, 215, 226, 234, 244, 257, 270, 283, 293, 305, 317, 332, 347}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
