// Code generated by "stringer -type=Type"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageDelete-0]
	_ = x[MessageUpdate-1]
	_ = x[MessagePurge-2]
	_ = x[MemberNickname-3]
	_ = x[MemberAvatar-4]
	_ = x[MemberRoles-5]
	_ = x[MemberTimeout-6]
	_ = x[MemberScreening-7]
	_ = x[MemberJoin-8]
	_ = x[MemberLeave-9]
	_ = x[MemberBan-10]
	_ = x[MemberUnban-11]
	_ = x[MemberKick-12]
	_ = x[RoleCreate-13]
	_ = x[RoleUpdate-14]
	_ = x[RoleDelete-15]
	_ = x[ServerEdited-16]
	_ = x[ServerEmoji-17]
	_ = x[UserName-18]
	_ = x[UserAvatar-19]
	_ = x[ChannelCreate-20]
	_ = x[ChannelUpdate-21]
	_ = x[ChannelDelete-22]
	_ = x[InviteSend-23]
	_ = x[InviteCreate-24]
	_ = x[InviteDelete-25]
	_ = x[VoiceConnection-26]
	_ = x[VoiceAudioState-27]
}

const _Type_name = "MessageDeleteMessageUpdateMessagePurgeMemberNicknameMemberAvatarMemberRolesMemberTimeoutMemberScreeningMemberJoinMemberLeaveMemberBanMemberUnbanMemberKickRoleCreateRoleUpdateRoleDeleteServerEditedServerEmojiUserNameUserAvatarChannelCreateChannelUpdateChannelDeleteInviteSendInviteCreateInviteDeleteVoiceConnectionVoiceAudioState"

var _Type_index = [...]uint16{0, 13, 26, 38, 52, 64, 75, 88, 103, 113, 124, 133, 144, 154, 164, 174, 184, 196, 207, 215, 225, 238, 251, 264, 274, 286, 298, 313, 328}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
