// Code generated by "stringer -type=Type"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[MessageDelete-1]
	_ = x[MessageUpdate-2]
	_ = x[MessagePurge-3]
	_ = x[MemberNickname-4]
	_ = x[MemberAvatar-5]
	_ = x[MemberRoles-6]
	_ = x[MemberTimeout-7]
	_ = x[MemberScreening-8]
	_ = x[MemberJoin-9]
	_ = x[MemberLeave-10]
	_ = x[MemberBan-11]
	_ = x[MemberUnban-12]
	_ = x[MemberKick-13]
	_ = x[RoleCreate-14]
	_ = x[RoleUpdate-15]
	_ = x[RoleDelete-16]
	_ = x[ServerEdited-17]
	_ = x[ServerEmoji-18]
	_ = x[UserName-19]
	_ = x[UserAvatar-20]
	_ = x[ChannelCreate-21]
	_ = x[ChannelUpdate-22]
	_ = x[ChannelDelete-23]
	_ = x[InviteSend-24]
	_ = x[InviteCreate-25]
	_ = x[InviteDelete-26]
	_ = x[VoiceConnection-27]
	_ = x[VoiceAudioState-28]
}

const _Type_name = "UnknownMessageDeleteMessageUpdateMessagePurgeMemberNicknameMemberAvatarMemberRolesMemberTimeoutMemberScreeningMemberJoinMemberLeaveMemberBanMemberUnbanMemberKickRoleCreateRoleUpdateRoleDeleteServerEditedServerEmojiUserNameUserAvatarChannelCreateChannelUpdateChannelDeleteInviteSendInviteCreateInviteDeleteVoiceConnectionVoiceAudioState"

var _Type_index = [...]uint16{0, 7, 20, 33, 45, 59, 71, 82, 95, 110, 120, 131, 140, 151, 161, 171, 181, 191, 203, 214, 222, 232, 245, 258, 271, 281, 293, 305, 320, 335}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
