// Code generated by "stringer -type=TimeFormat -linecomment"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShortTime-1]
	_ = x[LongTime-2]
	_ = x[ShortDate-3]
	_ = x[LongDate-4]
	_ = x[ShortDateTime-5]
	_ = x[LongDateTime-6]
	_ = x[Relative-7]
}

const _TimeFormat_name = "tTdDfFR"

var _TimeFormat_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7}

func (i TimeFormat) String() string {
	i -= 1
	if i < 0 || i >= TimeFormat(len(_TimeFormat_index)-1) {
		return "TimeFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TimeFormat_name[_TimeFormat_index[i]:_TimeFormat_index[i+1]]
}
