// Code generated by "stringer -type=AuditType -trimprefix=Audit"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuditMessageDelete-0]
	_ = x[AuditMessageUpdate-1]
	_ = x[AuditMessagePurge-2]
	_ = x[AuditMemberNickname-3]
	_ = x[AuditMemberAvatar-4]
	_ = x[AuditMemberRoles-5]
	_ = x[AuditMemberTimeout-6]
	_ = x[AuditMemberScreening-7]
	_ = x[AuditMemberJoin-8]
	_ = x[AuditMemberLeave-9]
	_ = x[AuditMemberBan-10]
	_ = x[AuditMemberUnban-11]
	_ = x[AuditMemberKick-12]
	_ = x[AuditRoleCreate-13]
	_ = x[AuditRoleUpdate-14]
	_ = x[AuditRoleDelete-15]
	_ = x[AuditServerEdited-16]
	_ = x[AuditServerEmoji-17]
	_ = x[AuditUserName-18]
	_ = x[AuditUserAvatar-19]
	_ = x[AuditChannelCreate-20]
	_ = x[AuditChannelUpdate-21]
	_ = x[AuditChannelDelete-22]
	_ = x[AuditChannelPermissionUpdate-23]
	_ = x[AuditInviteSend-24]
	_ = x[AuditInviteCreate-25]
	_ = x[AuditInviteDelete-26]
	_ = x[AuditVoiceState-27]
}

const _AuditType_name = "MessageDeleteMessageUpdateMessagePurgeMemberNicknameMemberAvatarMemberRolesMemberTimeoutMemberScreeningMemberJoinMemberLeaveMemberBanMemberUnbanMemberKickRoleCreateRoleUpdateRoleDeleteServerEditedServerEmojiUserNameUserAvatarChannelCreateChannelUpdateChannelDeleteChannelPermissionUpdateInviteSendInviteCreateInviteDeleteVoiceState"

var _AuditType_index = [...]uint16{0, 13, 26, 38, 52, 64, 75, 88, 103, 113, 124, 133, 144, 154, 164, 174, 184, 196, 207, 215, 225, 238, 251, 264, 287, 297, 309, 321, 331}

func (i AuditType) String() string {
	if i >= AuditType(len(_AuditType_index)-1) {
		return "AuditType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuditType_name[_AuditType_index[i]:_AuditType_index[i+1]]
}
