// Code generated by "stringer -type=changeType -linecomment"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[created-0]
	_ = x[deleted-1]
	_ = x[updated-2]
	_ = x[permissionsUpdated-3]
	_ = x[archived-4]
}

const _changeType_name = "createddeletedupdatedpermissions updatedarchived"

var _changeType_index = [...]uint8{0, 7, 14, 21, 40, 48}

func (i changeType) String() string {
	if i >= changeType(len(_changeType_index)-1) {
		return "changeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _changeType_name[_changeType_index[i]:_changeType_index[i+1]]
}
